JS-Algorithm/JS_ALGORITHM_STUDY

hyosin-Jang/230314/11058.js, hyosin-Jang/230314/README.md, hyosin-Jang/230314/주차요금계산.js, hyosin-Jang/230314/호텔대실.js
1. [크리보드](https://www.acmicpc.net/problem/11058)
2. [주차요금계산](https://school.programmers.co.kr/learn/courses/30/lessons/92341)
3. [호텔대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
- 기존에 C++로 PS를 해와서 우선 자바스크립트로 PS하는 방법을 익혔습니다. 
- 백준에서 node.js로 입/출력 받는 기본적인 방법과 PS에 쓰이는 주요 자바스크립트 메서드들을 공부했는데 아직 익숙치 않아서 체화시켜야할 것 같습니다.
- 준비 시간이 부족해서 모든 문제를 풀지는 못했는데, 다음 주부터는 준비 시간을 넉넉하게 잡아서 문제 풀이 뿐만 아니라 최적화된 풀이를 고민해보고 싶습니다.
=> # 20230314 hyosin-Jang (장효신) 문제 풀이 업로드

.gitignore, alsrb0504/20230404/problems.md, alsrb0504/20230404/광물 캐기/광물 캐기.js, alsrb0504/20230404/귤 고르기/귤 고르기.js, alsrb0504/20230404/그렇고 그런 사이/그렇고 그런 사이.js, alsrb0504/20230404/늑대와 올바른 단어/늑대와 올바른 단어.js, alsrb0504/20230404/메뉴 리뉴얼/메뉴 리뉴얼.js
1. [광물 캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
2. [귤 고르기](https://school.programmers.co.kr/learn/courses/30/lessons/138476)
3. [그렇고 그런 사이](https://www.acmicpc.net/problem/20921)
4. [늑대와 올바른 단어](https://www.acmicpc.net/problem/13022)
5. [메뉴 리뉴얼](https://school.programmers.co.kr/learn/courses/30/lessons/72411)
이번주 문제들을 풀이하며 제가 풀이한 방식 외에도 다른 방법으로도 풀이할 수 있겠다고 생각했습니다. 특히 그렇고 그런 사이 문제와 메뉴 리뉴얼 문제의 경우 구현 방식이 다양한 것이라 예상합니다. 다른 분들은 어떤 풀이 방식으로 풀이했는지 궁금합니다. ㅎㅎ
=> # 20230404 alsrb0504 (태민규) 문제 풀이 업로드

.github/workflows/auto-assign-reviewer.yml, README.md
- 레포지토리 README.md 파일을 .github 과 맞게 싱크
- GA 잘 되는지 한번 더 테스트 해보기 위해서 PR 개설
=> docs: 레포지토리 README.md 수정

.github/CODEOWNERS, JeeeunOh/test.js
=> test: PR Auto Assign 관련 테스트

alsrb0504/20230502/2개 이하로 다른 비트/2개 이하로 다른 비트.js, alsrb0504/20230502/problems.md, alsrb0504/20230502/블록 이동하기/블록 이동하기.js, alsrb0504/20230502/알약/알약.js, alsrb0504/20230502/이모티콘 할인 행사/이모티콘 할인 행사.js, alsrb0504/20230502/최고의 집합/최고의 집합.js
1. [최고의 집합](https://school.programmers.co.kr/learn/courses/30/lessons/12938)
2. [2개 이하로 다른 비트](https://school.programmers.co.kr/learn/courses/30/lessons/77885)
3. [알약](https://www.acmicpc.net/problem/4811)
4. [이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
5. [블록 이동하기](https://school.programmers.co.kr/learn/courses/30/lessons/60063)
개인적으로 이번주 문제들을 풀기 위해 DP, 그래프 탐색(DFS), 그리디, 수학 등 다양한 풀이를 사용할 수 있어 재밌게 풀이할 수 있었습니다. 제가 풀이한 방식 외에도 다른 방법으로도 문제를 해결할 수 있을 것 같다고 느꼈는데 다른 분들은 이번주 문제를 어떻게 풀이하셨는지 궁금합니다. 😄😄
=> # 20230502 alsrb0504 (태민규) 문제 풀이 업로드

hyosin-Jang/230509/삼각달팽이.js, hyosin-Jang/230509/숫자변환하기.js, hyosin-Jang/230509/타겟넘버.js, hyosin-Jang/230509/테이블해시함수.js
1. [Lv. 2] 숫자변환하기
https://school.programmers.co.kr/learn/courses/30/lessons/154538
2. [Lv. 2] 삼각달팽이
https://school.programmers.co.kr/learn/courses/30/lessons/68645
3. [Lv.2] 타겟 넘버
https://school.programmers.co.kr/learn/courses/30/lessons/43165
4. [Lv. 2] 테이블 해시 함수
https://school.programmers.co.kr/learn/courses/30/lessons/147354
아직 한 문제가 남았는데 스터디 전까지 도전해보겠습니다 !!
=> # 20230509 hyosin-Jang (장효신) 문제 풀이 업로드

Doozuu/230704/README.md, Doozuu/230704/boj5014_스타트링크.js, Doozuu/230704/boj9020_골드바흐의추측.js, Doozuu/230704/pro_공원산책.js, Doozuu/230704/pro_삼각달팽이.js
👇🏻 상세 풀이 Velog 정리
1. [백준 | 실버1 | 스타트링크(14500번)](https://velog.io/@049494/%EC%8B%A4%EB%B2%84-1-5014%EB%B2%88-%EC%8A%A4%ED%83%80%ED%8A%B8%EB%A7%81%ED%81%AC)
2. [백준 | 실버2 | 골드바흐의 추측(14499번)](https://velog.io/@049494/%EC%8B%A4%EB%B2%84-2-9020%EB%B2%88-%EA%B3%A8%EB%93%9C%EB%B0%94%ED%9D%90%EC%9D%98-%EC%B6%94%EC%B8%A1)
3. [프로그래머스 | Lv2 | 삼각 달팽이(1107번)](https://velog.io/@049494/Level-2-%EC%82%BC%EA%B0%81%EB%8B%AC%ED%8C%BD%EC%9D%B4)
4. [프로그래머스 | Lv1 | 공원 산책](https://velog.io/@049494/Level-1-%EA%B3%B5%EC%9B%90-%EC%82%B0%EC%B1%85)
5. [프로그래머스 | Lv2 | n진수 게임](https://school.programmers.co.kr/learn/courses/30/lessons/17687)
스타트링크는 BFS를 연습해볼 수 있어서 좋았고, 골드바흐의 추측은 답이 여러개일 때 가장 차이가 작은 값을 찾는 방법을 다양하게 생각해 볼 수 있었습니다. 삼각 달팽이와 공원 산책은 개인적으로 풀어보고 싶었던 문제였는데, 공원 산책이 특히 테스트케이스에서 고려해야할 부분이 많았던 것 같습니다.
n진수 게임은 시간상 풀지 …
=> # 20230704 Doozuu (이주희) 문제 풀이 업로드

Doozuu/230718/README.md, Doozuu/230718/boj1013_Contact.js, Doozuu/230718/boj13549_숨바꼭질3.js, Doozuu/230718/boj1713_후보추천하기.js, Doozuu/230718/pro_거리두기확인하기.js
1. [백준 | 실버1 | 후보 추천하기](https://velog.io/@049494/%EC%8B%A4%EB%B2%84-1-1713%EB%B2%88-%ED%9B%84%EB%B3%B4-%EC%B6%94%EC%B2%9C%ED%95%98%EA%B8%B0)
2. [백준 | 골드5 | 숨바꼭질3 ](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-13549%EB%B2%88-%EC%88%A8%EB%B0%94%EA%BC%AD%EC%A7%88-3)
3. [프로그래머스 | Lv2 | 양궁대회 ]()
4. [백준 | 골드5 | Contact ](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-1013%EB%B2%88-Contact)
5. [프로그래머스 | Lv2 | 거리두기 확인하기](https://velog.io/@049494/Level-2-%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0-%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0)
- 후보 추천하기 : 처음 생각한 풀이가 틀려서 찾아봤는데 왜 틀린건지 잘 모르겠네요. 한 번 풀이 봐주시면 감사하겠습니다!
- 숨바꼭질 : 그냥 큐를 이용해서 풀었을 때 시간초과가 났는데, 우선순위를 고려해서 짜야 된다는 걸 새롭게 배웠습니다.
- Contact : 잘모르겠어서 찾아봤는데 이걸 정규표현식으로 이렇게 간단하게 풀 수 있는 줄은 몰랐네요..
- 거리두기 확인하기 : 삼중 반복문으로 풀려고 하다가 이건 아닌것 같아서 결국 찾아봤습니다. 침착하게 풀면 풀 수 있을 것 같기도 …
=> # 20230718 doozuu (이주희) 문제 풀이 업로드

JeeeunOh/230725/README.md, JeeeunOh/230725/게임맵최단거리.js, JeeeunOh/230725/순위검색.js, JeeeunOh/230725/오픈채팅방.js, JeeeunOh/230725/이모티콘할인행사.js, JeeeunOh/230725/프로세스.js
1. [[LV. 2] 이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368) 
2. [[LV. 2] 순위검색](https://school.programmers.co.kr/learn/courses/30/lessons/72412)
3. [[LV. 2] 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888) 
4. [[LV. 2] 게임 맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844) 
5. [[LV. 2] 프로세스](https://school.programmers.co.kr/learn/courses/30/lessons/42587) 
순위검색을 이전에 풀었어서 이분탐색이라는 것을 알았는데도 어려웠습니다...
제 방식대로 풀면 효율성 초과에서 오류가 나서 답지를 참고했습니다..ㅎㅎ
구조체가 아니라 Map 객체를 쓰면 자꾸 효율성에서 시간초과가 나는데 무슨 일인지 모르겠네요 ㅜ
=> # 20230725 JeeeunOh (오지은) 문제 풀이 업로드

stakbucks/230725/README.md, stakbucks/230725/p_150368_이모티콘할인행사.js, stakbucks/230725/p_1844_게임맵최단거리.js, stakbucks/230725/p_42587_프로세스.js, stakbucks/230725/p_42888_오픈채팅방.js, stakbucks/230725/p_72412_순위검색.js
1. [[LV2] 이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
2. [[LV2] 순위검색](https://school.programmers.co.kr/learn/courses/30/lessons/72412)
3. [[LV2] 오픈채팅방](https://school.programmers.co.kr/learn/courses/30/lessons/42888)
4. [[LV2] 게임 맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844)
5. [[LV2] 프로세스](https://school.programmers.co.kr/learn/courses/30/lessons/42587)
- [[LV2] 순위검색](https://school.programmers.co.kr/learn/courses/30/lessons/72412) 문제 너무 어려웠습니다. 이게 왜 lv2인지 모르겠네요ㅠ 효율성 문제 해결하지 못한 풀이만 올리겠습니다.
=> # 20230725 stakbucks (황태환) 문제 풀이 업로드

Doozuu/230725/pro_게임맵최단거리.js, Doozuu/230725/pro_오픈채팅방.js, Doozuu/230725/pro_프로세스.js
3문제 밖에 못 풀긴 했지만 이번에는 문제 풀이를 찾아보지 않고 전부 제 힘으로 풀었다는 점이 뿌듯했습니다!
게임 맵 최단거리에서는 큐를 직접 구현해 풀어보았습니다.
=> # 20230725 Doozuu (이주희) 문제 풀이 업로드

Doozuu/230808/README.md, Doozuu/230808/boj13549_숨바꼭질3.js, Doozuu/230808/pro_JadenCase문자열만들기.js, Doozuu/230808/pro_메뉴리뉴얼.js, Doozuu/230808/pro_의상.js, Doozuu/230808/pro_할인행사.js
1. [프로그래머스 | Lv2 | 메뉴 리뉴얼 ](https://velog.io/@049494/Level-2-%EB%A9%94%EB%89%B4-%EB%A6%AC%EB%89%B4%EC%96%BC)
2. [프로그래머스 | Lv2 | JadenCase 문자열 만들기](https://velog.io/@049494/Level-2-JadenCase-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%A7%8C%EB%93%A4%EA%B8%B0)
3. [백준 | 골드 5 | 숨바꼭질3 ](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-13549%EB%B2%88-%EC%88%A8%EB%B0%94%EA%BC%AD%EC%A7%88-3)
4. [프로그래머스 | Lv2 | 의상 ](https://velog.io/@049494/Level-2-%EC%9D%98%EC%83%81)
5. [프로그래머스 | Lv2 | 할인행사](https://velog.io/@049494/Level-2-%ED%95%A0%EC%9D%B8-%ED%96%89%EC%82%AC)
- `의상` 문제에서 수학 규칙성을 발견하는 부분이 굉장히 신기했습니다.
- `메뉴 리뉴얼`문제에서 조합을 이용해야겠다는 생각은 들었는데, 조합 구하는 함수가 생각이 안나서 찾아봤습니다. 
다음엔 직접 구현할 수 있도록 꼼꼼히 이해해보겠습니다!
=> # 20230808 doozuu (이주희) 문제 풀이 업로드

Doozuu/230814/REAMD.md, Doozuu/230814/boj2565_전깃줄.js, Doozuu/230814/pro_더맵게.js, Doozuu/230814/pro_전화번호목록.js, Doozuu/230814/pro_주식가격.js, Doozuu/230814/pro_주차요금계산.js
1. [백준 | 골드 5 | 전깃줄 ](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-2565%EB%B2%88.-%EC%A0%84%EA%B9%83%EC%A4%84)
2. [프로그래머스 | Lv2 | 주차 요금 계산 ](https://velog.io/@049494/Level-2-%EC%A3%BC%EC%B0%A8-%EC%9A%94%EA%B8%88-%EA%B3%84%EC%82%B0)
3. [프로그래머스 | Lv2 | 전화번호 목록](https://velog.io/@049494/Level-2-%EC%A0%84%ED%99%94%EB%B2%88%ED%98%B8-%EB%AA%A9%EB%A1%9D)
4. [프로그래머스 | Lv2 | 더 맵게 ](https://velog.io/@049494/Level-2-%EB%8D%94-%EB%A7%B5%EA%B2%8C)
5. [프로그래머스 | Lv2 | 주식가격](https://velog.io/@049494/Level-2-%EC%A3%BC%EC%8B%9D-%EA%B0%80%EA%B2%A9-5qrzkfse)
- `전깃줄` : 가장 긴 오름차순 부분 수열의 길이를 구하기 위해 dp를 활용할 수 있다는 점이 인상깊었습니다.
- `주차 요금 계산` : 조금 비효율적으로 푼 것 같아서 다른 분들은 어떻게 푸셨을지 궁금하네요!
- `전화번호 목록` : string 타입의 숫자는 sort를 쓰면 사전순으로 정렬해준다는 점을 다시금 상기시킬 수 있었습니다.
- `더 맵게` : 처음 푼 풀이가 효율성 테스트를 통과하지 못해서 풀이를 찾아봤는데, 최소 힙을 이용해 푸는 …
=> # 20230815 doozuu (이주희) 문제 풀이 업로드 

Doozuu/230822/README.md, Doozuu/230822/boj14395_4연산.js, Doozuu/230822/boj9084_동전.js, Doozuu/230822/pro_뉴스클러스터링.js, Doozuu/230822/pro_압축.js, Doozuu/230822/pro_전력망을둘로나누기.js
1. [골드 5 | 동전](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-9084%EB%B2%88-%EB%8F%99%EC%A0%84)
2. [LV 2 | 전력망을 둘로 나누기](https://velog.io/@049494/Level-2-%EC%A0%84%EB%A0%A5%EB%A7%9D%EC%9D%84-%EB%91%98%EB%A1%9C-%EB%82%98%EB%88%84%EA%B8%B0)
3. [Lv2 | 뉴스 클러스터링](https://velog.io/@049494/Level-2-1%EC%B0%A8-%EB%89%B4%EC%8A%A4-%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81)
4. [Lv2 | 압축](https://velog.io/@049494/Level-2-3%EC%B0%A8-%EC%95%95%EC%B6%95)
5. [골드 5 | 4연산](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-5-14395%EB%B2%88-4%EC%97%B0%EC%82%B0)
`동전`이랑 `전력망 둘로 나누기`만 풀이를 찾아봤습니다.(아직 dp가 많이 어렵네요..^^)
전체적으로 효율적으로 풀지는 못한 것 같아 아쉽지만, 최대한 혼자 힘으로 풀어보려 노력했습니다.😌
=> # 20230822 doozuu (이주희) 문제 풀이 업로드

Hyeple/230829/LV2_롤케이크자르기.js, Hyeple/230829/LV2_택배상자.js, Hyeple/230829/README.md, Hyeple/230829/골드5_평범한배낭.js, Hyeple/230829/골드5_풍선맞추기.js, Hyeple/230829/골드5_회문.js
1. [골드5] 회문 https://www.acmicpc.net/problem/17609
2. [골드5] 풍선 맞추기 https://www.acmicpc.net/problem/11509
3. [Lv2] 롤케이크 자르기 https://school.programmers.co.kr/learn/courses/30/lessons/132265
4. [Lv2] 택배상자 https://school.programmers.co.kr/learn/courses/30/lessons/131704
5. [골드5] 평범한 배낭 https://www.acmicpc.net/problem/12865
https://hw-ple.notion.site/20230829-13e3dc1ae3b94792a50ccc4c27fd1de6?pvs=4
이번에는 전반적으로 코드가 쉽고 간결하게 짜졌던 것 같습니다.
문제를 이해하는데 좀 시간이 걸리고, 특별한 설계가 필요하다기보다는 이해한 그대로 문제를 코드로 적어내는 느낌이였습니다.
특별한 알고리즘이 어울리겠다! 라고 푼 문제가 배낭 문제를 제외하고는 없는 거 같아서...
다른 분들 풀이가 궁금합니당.
=> #20230829 Hyeple (장혜원) 문제 풀이 업로드

Hyeple/230905/LV2_혼자놀기의달인.js, Hyeple/230905/README.md, Hyeple/230905/골드1_k번째수.js, Hyeple/230905/골드4_스도쿠.js, Hyeple/230905/골드4_알파벳.js, Hyeple/230905/골드5_수나누기게임.js
1. [골드1] k번째 수 https://www.acmicpc.net/problem/1300
2. [골드4] 알파벳 https://www.acmicpc.net/problem/1987
3. [골드4] 스도쿠 https://www.acmicpc.net/problem/2239
4. [골드5] 수나누기게임 https://www.acmicpc.net/problem/27172
5. [LV2] 혼자 놀기의 달인 https://school.programmers.co.kr/learn/courses/30/lessons/131130
https://hw-ple.notion.site/20230905-a7a6c19984094612af87129a176d2364?pvs=4
혼자 놀기의 달인 문제가 정말 이해가 안되서, 다른 코드들을 참고해서 풀었습니다. ㅖ 슬픕니다.
문제 푼게 제 아이디어가 아니기도 하고, 굳이 temp 배열이 필요할까? 싶습니다.
아무튼 좀 더 괜찮은 풀이가 있을 것 같아서 고민해볼 생각입니다.
알파벳 문제에서 재귀 호출이 좀 많은건지, 아무래도 시간 초과가 좀 아슬아슬한 거 같아서, 저 부분을 좀 더 최적화할 수 있는 방법이 있을지 고민하고 있습니다.
=> #20230905 Hyeple (장혜원) 문제 풀이 업로드

Hyeple/230919/Lv2_땅따먹기.js, Hyeple/230919/Lv2_리코쳇로봇.js, Hyeple/230919/Lv2_멀리뛰기.js, Hyeple/230919/Lv2_시소짝꿍.js, Hyeple/230919/README.md, Hyeple/230919/골드4_함께블록쌓기.js
1. [골드4] 함께 블록쌓기 https://www.acmicpc.net/problem/18427
2. [Lv2] 땅따먹기 https://school.programmers.co.kr/learn/courses/30/lessons/12913
3. [Lv2] 리코쳇 로봇 https://school.programmers.co.kr/learn/courses/30/lessons/169199
4. [Lv2] 시소 짝꿍 https://school.programmers.co.kr/learn/courses/30/lessons/152996
5. [LV2] 멀리 뛰기 https://school.programmers.co.kr/learn/courses/30/lessons/12914
멀리 뛰기 문제가 꽤나 단순하면서도 풀이법이 다양해서 읽느라 재밌었어요.
시소짝꿍이 어떤 알고리즘을 쓰면 좋을지 고민하다가, 그리디로 풀었는데 dp로 푼 경우도 있는 거 같고, 다양한 풀이를 함 봐보고 싶습니다.
=> # 20230919 Hyeple (장혜원) 문제 풀이 업로드

stakbucks/230926/README.md, stakbucks/230926/p_147354_테이블해시함수.js, stakbucks/230926/p_154538_숫자변환하기.js, stakbucks/230926/p_17683_방금그곡.js, stakbucks/230926/p_49993_스킬트리.js, stakbucks/230926/p_72412_순위정렬.js
1. [[Lv 2] 방금그곡](https://school.programmers.co.kr/learn/courses/30/lessons/17683)
2. [[Lv 2] 스킬트리](https://school.programmers.co.kr/learn/courses/30/lessons/49993)
3. [[LV2] 순위 정렬](https://school.programmers.co.kr/learn/courses/30/lessons/72412)
4. [[Lv.2] 숫자 변환하기](https://school.programmers.co.kr/learn/courses/30/lessons/154538)
5. [[Lv.2] 테이블 해시 함수](https://school.programmers.co.kr/learn/courses/30/lessons/147354)
- [[LV2] 순위 정렬](https://school.programmers.co.kr/learn/courses/30/lessons/72412) 효율성 테스트 통과 못했습니다. 
제 풀이 방식은: 
Map 생성 
-> DFS로 '-' 가 포함된 경우까지 처리해서 Map에 저장 
-> Map 순회하며 정렬 
-> query 순회하며 각 query에 해당하는 값 Map에서 가져옴 
-> 이진 탐색으로 특정 점수 이상인 경우 카운트
어디서 시간초과가 나는지 잘 모르겠습니다. DFS 때문에 시간초과가 나는 줄 알았는데, 그 부분만 다른 사람들 풀이를 참고한 방식으로 바꾸니 오히려 시간이 늘어났습니다 ㅠ
- 나머지 문제들은 무난했던 거 같습니다. 
- 자바스크립트에서 ^ 로 …
=> # 20230926 stakbucks (황태환) 문제 풀이 업로드

Doozuu/231003/README.md, Doozuu/231003/boj14502_연구소.js, Doozuu/231003/boj2631_줄세우기.js, Doozuu/231003/pro_우박수열정적분.js, Doozuu/231003/pro_점찍기.js, Doozuu/231003/pro_혼자놀기의달인.js
👇🏻 상세 풀이 Velog 정리
1. [Lv2 | 점 찍기](https://velog.io/@049494/Level-2-%EC%A0%90-%EC%B0%8D%EA%B8%B0)
2. [Lv 2 | 우박수열 정적분](https://velog.io/@049494/Level-2-%EC%9A%B0%EB%B0%95%EC%88%98%EC%97%B4-%EC%A0%95%EC%A0%81%EB%B6%84)
3. [Lv 2 | 혼자 놀기의 달인](https://velog.io/@049494/Level-2-%ED%98%BC%EC%9E%90-%EB%86%80%EA%B8%B0%EC%9D%98-%EB%8B%AC%EC%9D%B8)
4. [골드4 | 줄세우기](https://velog.io/@049494/%EA%B3%A8%EB%93%9C-4-2631%EB%B2%88-%EC%A4%84%EC%84%B8%EC%9A%B0%EA%B8%B0)
5. [골드4 | 연구소](https://www.acmicpc.net/problem/14502)
점 찍기 문제에서 처음에 시간초과가 발생했는데, x^2 + y^2 = d^2 성질을 역으로 이용해 다른 좌표의 최댓값을 구해서 해결했습니다. 
줄 세우기 문제와 연구소 문제는 어려워서 풀이를 찾아보았습니다.
=> # 20231004 doozuu(이주희) 문제 풀이 업로드 

Doozuu/231010/boj2566_전깃줄.js, Doozuu/231010/pro_과제진행하기.js, Doozuu/231010/pro_숫자카드나누기.js
1. [[Gold V] 트리와 쿼리](https://www.acmicpc.net/problem/15681) ❌
2. [[Lv. 2] 교점에 별 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/87377) ❌
4. [[Lv. 2] 과제 진행하기](https://school.programmers.co.kr/learn/courses/30/lessons/176962)
5. [[Gold V] 전깃줄](https://www.acmicpc.net/problem/2565) 
6. [[Lv. 2] 숫자 카드 나누기](https://www.acmicpc.net/problem/14502)
1,2번 문제는 시간 관계상 풀지 못하였습니다ㅠㅠ 다음부터 꼭 다 풀어오겠습니다!!
=> # 20231010 doozuu(이주희) 문제 풀이 업로드 

Doozuu/231024/boj10422_괄호.js, Doozuu/231024/boj17144_미세먼지안녕!.js, Doozuu/231024/boj5557_1학년.js, Doozuu/231024/pro_다리를지나는트럭.js, Doozuu/231024/pro_쿼드압축후개수세기.js
1. [[골드 4] 미세먼지 안녕!](https://www.acmicpc.net/problem/17144)
2. [[골드5] 1학년](https://www.acmicpc.net/problem/5557)
3. [[골드4] 괄호](https://www.acmicpc.net/problem/10422)
4. [[Lv2] 다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
5. [[Lv2] 쿼드압축 후 개수 세기](https://school.programmers.co.kr/learn/courses/30/lessons/68936)
1학년 문제와 괄호 문제는 풀이를 참조해 풀었습니다!
카탈란 수가 있다는 걸 처음 알았네요😮
=> # 20231024 doozuu (이주희) 문제 풀이 업로드 

Doozuu/231031/boj16935_배열돌리기3.js, Doozuu/231031/boj2133_타일채우기.js, Doozuu/231031/pro_배댤.js, Doozuu/231031/pro_줄서는방법.js
1. [[골드4] 타일 채우기](https://www.acmicpc.net/problem/2133)
2. [[골드5] 파이프 옮기기1](https://www.acmicpc.net/problem/17070)
3. [[골드5] 배열 돌리기](https://www.acmicpc.net/problem/16935)
4. [[Lv2] 배달](https://school.programmers.co.kr/learn/courses/30/lessons/12978)
5. [[Lv2] 줄 서는 방법](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
파이프 옮기기 문제를 제외하고 4문제를 풀었습니다.
배열 돌리기3 문제는 계속 시도해봤는데 실패했습니다ㅠㅠ
=> #20231031 doozuu (이주희) 문제 풀이 업로드

Hyeple/231031/백준_16935.js, Hyeple/231031/백준_17070.js, Hyeple/231031/백준_2133.js, Hyeple/231031/프로그래머스_배달.js, Hyeple/231031/프로그래머스_줄서는방법.js
[[백준 골드4] 타일 채우기](https://www.acmicpc.net/problem/2133)
[[백준 골드5] 파이프 옮기기1](https://www.acmicpc.net/problem/17070)
[[백준 골드5] 배열 돌리기](https://www.acmicpc.net/problem/16935)
[[프로그래머스 Lv2] 배달](https://school.programmers.co.kr/learn/courses/30/lessons/12978)
[[프로그래머스 Lv2] 줄 서는 방법](https://school.programmers.co.kr/learn/courses/30/lessons/12936)
배열돌리기의 op5, op6 부분은 아이디어가 정말 잘 생각나지 않아 검색을 했습니다.
배열 부분은 머리에서 숫자가 빙빙 돌면서 잘 그려지지 않는 것 같습니다.
최근 학교 수업 때문에 js가 아니라 파이썬으로 코딩테스트 문제를 풀고 있는데, 두 개가 섞이니 너무 혼란스럽습니다.
=> #20231031 Hyeple (장혜원) 문제 풀이 업로드

Doozuu/231114/boj11399_ATM.js, Doozuu/231114/boj1783_병든나이트.js, Doozuu/231114/pro_가장큰수.js, Doozuu/231114/pro_숫자블록.js, Doozuu/231114/pro_피로도.js
1. [Lv 2  | 숫자 블록](https://school.programmers.co.kr/learn/courses/30/lessons/12923)
2. [실버 4 | ATM](https://www.acmicpc.net/problem/11399)
3. [Lv2 | 가장 큰수](https://school.programmers.co.kr/learn/courses/30/lessons/42746)
4. [Lv.2 | 피로도](https://school.programmers.co.kr/learn/courses/30/lessons/87946)
5. [실버 3 | 병든 나이트](https://www.acmicpc.net/problem/1783)
숫자 블록 문제에서 자꾸 효율성 통과가 안되는데 어떻게 해결해야할 지 모르겠네요ㅠㅜ
=> # 20231114 doozuu (이주희) 문제 풀이 업로드

Doozuu/231121/boj19539_사과나무.js, Doozuu/231121/pro_가장큰정사각형찾기.js, Doozuu/231121/pro_게임맵최단거리.js, Doozuu/231121/pro_뒤에있는큰수찾기.js, Doozuu/231121/pro_연속부분수열합의개수.js
1. [[Lv 2] 뒤에 있는 큰 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/154539)
2. [[Lv 2] 가장 큰 정사각형 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/12905)
3. [[Lv.2] 연속 부분 수열 합의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/131701)
4. [[Lv.2] 게임맵 최단거리](https://school.programmers.co.kr/learn/courses/30/lessons/1844)
5. [[골드5] 사과나무](https://www.acmicpc.net/problem/19539)
이전에 풀었던 문제들이 있어서 복습하며 풀었습니다!
=> # 20231121 doozuu (이주희) 문제 풀이 업로드 

Hyeple/231114/boj_11399.js, Hyeple/231114/boj_1783.js, Hyeple/231114/pro_12923.js, Hyeple/231114/pro_42746.js, Hyeple/231114/pro_87946.js
1. [Lv 2] 숫자 블록 https://school.programmers.co.kr/learn/courses/30/lessons/12923
2. [실버 4] ATM https://www.acmicpc.net/problem/11399
3. [Lv2] 가장 큰수 https://school.programmers.co.kr/learn/courses/30/lessons/42746
4. [Lv.2] 피로도 https://school.programmers.co.kr/learn/courses/30/lessons/87946
5. [실버 3] 병든 나이트 https://www.acmicpc.net/problem/1783
전반적으로 확실히 문제가 간단했던거 같습니당.
전에 파이썬으로 피로도 문제를 풀었던 적이 있고, 그 때는 코드가 좀 더 짧았던거같은데 js로 짜니까 길어진 감이 있긴합니다.
=> # 20231114 Hyeple (장혜원) 문제 풀이 업로드

Doozuu/231127/boj4949_균형잡힌세상.js, Doozuu/231127/pro_K진수에서소수개수구하기.js, Doozuu/231127/pro_호텔대실.js
1. [[Lv2] k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
2. [[실버 4] 균형잡힌 세상](https://www.acmicpc.net/problem/4949)
3. [[LV 2] 호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
`균형잡힌 세상` 문제에서 조금 헤맸던 부분이 있어서 조언구하고 싶습니다!
for 문으로 돌렸을 때(맨 마지막은 . 이니까 마지막 바로 전까지만 순회)는 틀렸는데, for of 문으로 바꾸고 . 일 때 break하는 조건을 추가했더니 맞았습니다.
맨 마지막에만 .이 나오는게 아니라 중간에 . 이 나왔을 때도 반복문을 중단하고 현재까지의 결과를 출력해야 되서 그런 것 같다고 생각했는데 이게 원인인 걸까요? 아니면 다른 원인이 있는지 궁금합니다!
=> # 20231128 doozuu(이주희) 문제 풀이 업로드

stakbucks/231128/README.md, stakbucks/231128/b_4949_균형잡힌세상/app.js, stakbucks/231128/b_4949_균형잡힌세상/input.txt, stakbucks/231128/p_155651_호텔대실.js, stakbucks/231128/p_92335_k진수에서소수개수구하기.js
1. [[Lv2] k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
2. [[실버 4] 균형잡힌 세상](https://www.acmicpc.net/problem/4949)
3. [[LV 2] 호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
- 크게 어려운 문제는 없었습니다. [[LV 2] 호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
이 문제에서 삽질하느라 시간을 썼는데 좀 더 집중해서 빠르게 푸는 연습을 해야할 것 같다고 느꼈습니다.
=> # 20231128 stakbucks (황태환) 문제 풀이 업로드 

Doozuu/231205/pro_문자열압축.js, Doozuu/231205/pro_석유시추.js, Doozuu/231205/pro_신고결과받기.js, Doozuu/231205/pro_큰수만들기.js, Doozuu/231205/pro_택배배달과수거하기.js
1. [문자열 압축](https://school.programmers.co.kr/learn/courses/30/lessons/60057) 
2. [택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369)
3. [석유 시추](https://school.programmers.co.kr/learn/courses/30/lessons/250136)
4. [신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
5. [큰 수 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
- 문자열 압축은 좀 더 효율적으로 풀 수 있을거 같은데 조언주시면 감사하겠습니다!
- 택배 배달과 수거하기는 풀이를 찾아봤습니다. 이런 아이디어가 떠오르는게 신기하네요..^^
- 석유 시추는 효율성에서 통과가 안되었습니다.
=> # 20231205 doozuu (이주희) 문제 풀이 업로드

stakbucks/231205/README.md, stakbucks/231205/p_150369_택배배달과수거하기.js, stakbucks/231205/p_250136_석유시추.js, stakbucks/231205/p_42883_큰수만들기.js, stakbucks/231205/p_60057_문자열압축.js, stakbucks/231205/p_92334_신고결과받기.js
1. [문자열 압축](https://school.programmers.co.kr/learn/courses/30/lessons/60057) 
2. [택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369) - 못 품
3. [석유 시추](https://school.programmers.co.kr/learn/courses/30/lessons/250136)
4. [신고 결과 받기](https://school.programmers.co.kr/learn/courses/30/lessons/92334)
5. [큰 수 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/42883)
[택배 배달과 수거하기](https://school.programmers.co.kr/learn/courses/30/lessons/150369) 문제 해결하지 못했습니다. 다른 사람들 풀이 참고하고 제 방식대로 풀려고 했는데 잘 안되네요 ㅠ 더 열심히 하겠습니다
=> # 20231205 stakbucks (황태환) 문제 풀이 업로드 

Hyeple/231128/boj_4949.js, Hyeple/231128/pro_155651.js, Hyeple/231128/pro_92335.js
[1. [Lv2] k진수에서 소수 개수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/92335)
[2. [실버 4] 균형잡힌 세상](https://www.acmicpc.net/problem/4949)
[3. [LV 2] 호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
전에 파이썬으로 호텔 대실 문제를 풀었을때는 heapq로 쉽게 풀었던 기억이 있었는데, 왠지 js로 풀려니 잘 안되서 그냥 방향을 바꿔서 풀었습니다.
=> 20231128 Hyeple(장혜원) 문제 풀이 업로드

stakbucks/231212/README.md, stakbucks/231212/p_118666_성격유형검사하기.js, stakbucks/231212/p_150368_이모티콘할인행사.js, stakbucks/231212/p_17686_파일명정렬.js, stakbucks/231212/p_92343_양과늑대.js
1. [양과 늑대](https://school.programmers.co.kr/learn/courses/30/lessons/92343)
2. [성격 유형 검사하기](https://school.programmers.co.kr/learn/courses/30/lessons/118666)
3. [이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
4. [파일명 정렬](https://school.programmers.co.kr/learn/courses/30/lessons/17686)
- 이참에 정규식을 공부했습니다. match()도 처음 사용해봤습니다.
- 앞으로 https://stakbucks.tistory.com/ 블로그에 풀이를 상세히 업로드하려고 합니다. 이래야 단순히 문제 풀이에 그치지 않고 많이 얻어갈 수 있을 거 같아요. 제 코드에서 잘 이해가 안가는 부분이 있으면 참고해주세요.
=> # 20231212 stakbucks (황태환) 문제 풀이 업로드 
